DROP TABLE IF EXISTS mercancias;
create table mercancias (
ID SERIAL primary key,
NOMBRE VARCHAR (100) unique not null,
PRODUCTO VARCHAR (100) not null,
CANTIDAD INT not NULL,
FECHA_REG DATE NOT null);
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 1','PRODUCTO 1',1,'2021-10-18');
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 2','PRODUCTO 2',2,'2021-10-18');
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 3','PRODUCTO 3',3,'2021-10-18');
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 4','PRODUCTO 4',4,'2021-10-18');
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 5','PRODUCTO 5',5,'2021-10-18');
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 6','PRODUCTO 6',6,'2021-10-18');
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 7','PRODUCTO 7',7,'2021-10-18');
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 8','PRODUCTO 8',8,'2021-10-18');
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 9','PRODUCTO 9',9,'2021-10-18');
INSERT INTO MERCANCIAS(NOMBRE,PRODUCTO,CANTIDAD,FECHA_REG) VALUES ('NOMBRE 10','PRODUCTO 10',10,'2021-10-18');
